language: python
python:
- '3.5'
install:
- pip3 install HookTest
script:  hooktest  --console table --scheme tei --workers 3 --verbose 5 --manifest --countword ./
before_deploy:
- hooktest-build --travis --txt ./
- results=$(cat manifest.txt)
- DATE=`date +%Y-%m-%d`
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$major_version.$minor_version.$TRAVIS_BUILD_NUMBER
- git add -A
- git tag $GIT_TAG -a -m "$DATE" -m "PASSING FILES" -m "$results"
- git push -q https://$GITPERM@github.com/hlapin/ancJewLitCTS --tags
- ls -R

deploy:
  provider: releases
  api_key: 2b370bfeba6028c0a1c7e0fff66f8874b16f49ed
  skip_cleanup: true
  on:
    repo: hlapin/ancJewLitCTS
    branch: master

env:
  global:
    major_version: 0
    minor_version: 0
